### ISSUE TITLE
wrong or expired session-id

### ISSUE THREAD

**Issue by svantetobias** [jsign/go-kzg-ceremony-client#6]
Hi!

Followed your guide to the point. Using version  1.0.3

After several hours I get 504 error and "err: wrong or expired session-id"`. More specifically:

```Still isn't our turn, waiting 30s for retrying...
Waiting for our turn to contribute...
Still isn't our turn, waiting 30s for retrying...
Waiting for our turn to contribute...
Waiting for our turn failed (err: received status code 504), retrying in 30s...
Waiting for our turn to contribute...
Waiting for our turn failed (err: wrong or expired session-id, login again with the sequencer), retrying in 30s...
Waiting for our turn to contribute...
Waiting for our turn failed (err: wrong or expired session-id, login again with the sequencer), retrying in 30s...
```

I've tried logging in again and restarting the `kzgcli` process, several times.

Anything else I can try or investigate?

**Comment by jsign** [comment]
@svantetobias , that 504 status code from the sequencer seems to indicate that the sequencer might be having some problems.

Some questions to guess a bit what might be happening:
- After you login again and try to contribute again, do you get the usual "waiting for our turn" messages?
- Do you always see this pattern of getting a 504 status code, and then the "wrong or expired session-id"?

**Comment by jsign** [comment]
@svantetobias, looks like there's a known issue in the sequencer regarding random logouts, which looks exactly as the problem you're describing.

Here's a screenshot from the #kzg-ceremony server:
![image](https://user-images.githubusercontent.com/6136245/212773420-938d0ea3-7ba7-4fa5-8884-c72e71bb0b64.png)

So it looks like this is affecting all clients. I'll keep track when this is announced that's fixed, but looks like it might be tomorrow.

**Comment by svantetobias** [comment]
Thanks!

**Comment by jsign** [comment]
@svantetobias, yes, the EF is fixing a related bug that logout users. The PR with the fix is https://github.com/ethereum/kzg-ceremony-sequencer/pull/176. I'll ping you when that gets merged and deployed.

**Comment by jsign** [comment]
@svantetobias, the PR from the sequencer that fixes this situation was merged and deployed.

Can you check again if you still have the logout problem?

(No new version of this client is needed, so you can use the same one you have)

**Comment by jsign** [comment]
Closing since I had confirmations from other users!
